src/JoomlaBrowser.php
Weblinks tests fail with timeout on installing Joomla, as it takes more than 10 seconds to delete and recreate all tables. With this PR, the timeout is 60 seconds, and it passes.
=> 10 seconds (even 30 seconds) not enough to install Joomla: change timeout to 60 seconds

src/JoomlaBrowser.php
Currently, the installJoomla() method searches for english label  **before** setting the language, so it is not working on different locales.
With this change, we only look for **elements** until we set the language, and then we're all good anyway.
P.S. I replaced with the checks that sound more obvious, but I'll be happy to get any better suggestion.
=> Avoid locale-related issues in installJoomla()

src/JoomlaBrowser.php
This pull updates #4 by moving locators to strict locators: https://docs.joomla.org/Testing_Joomla_Extensions_with_Codeception#Always_add_Strict_Locators_to_your_tests
cc: @zanardigit
=> move language selector to strict locator

src/JoomlaBrowser.php
Reverts joomla-projects/joomla-browser#5
reverts because selenium doesn't see hidden elements
=> Revert "move language selector to strict locator"

src/JoomlaBrowser.php
Now it waits until the button has changed it's state, meaning that the folder removal has suceed:
=> Wait until the Installation folder has been removed

src/JoomlaBrowser.php
If the database exists joomla tries to remove it but Joomla-Browser was not giving enough time to do it causing the installation to stall.
=> Avoid stalls while joomla is removing the database

src/JoomlaBrowser.php
The merge of https://github.com/joomla/joomla-cms/commit/587d8460e9cd700902b453ae8914c54ea4feb35d#diff-96a553a6573472300f4c6a8c6797ad19R30 related to the issue https://github.com/joomla/joomla-cms/pull/7490 caused JoomlaBrowser to not be able to install extensions. This commit updates the strings as needed
=> Update changed strings

README.md, src/JoomlaBrowser.php
This is a first approach to select items in Chosen Multiple:
It works but I see room for improvement, specially in the xPaths
=> Add select multiple options in chosen

README.md, src/JoomlaBrowser.php
@javigomez For the moment I propose we just add a new function to avoid failures and within a week we will delete the old function installExtensionFromDirectory and let others know about it.
=> Adding installExtensionFromFolder function

src/JoomlaBrowser.php
This command was wrong. It was waiting for a visibility change in the element, but the right check is not to check if visibilty is changed but if the element has appeared in the DOM.
=> Fix joomla installation folder removal false positives

src/JoomlaBrowser.php
This will allow to do installExtensionFromFolder('.../', 'Module'); or  installExtensionFromFolder('.../', 'Language');
=> Allow to install other types of extension

.gitignore, .travis.yml, README.md, RoboFile.php, composer.json, composer.lock
Uses https://github.com/joomla/coding-standards sniffers to check the code style of the project.
To check automatically the code style execute the following commands in your Terminal window at the root of the repository:
- `$ composer install`
- `$ vendor/bin/robo`
- `$ vendor/bin/robo check:codestyle`
=> Add code style checker based in Robo.li

src/JoomlaBrowser.php
This function allows to simply publish a module in frontend.
There is some tricks for this select:
Because it doesn't behaves as normal Chosen, making the "selectOptionInChosen" function not to work.
=> Publish module feature

src/JoomlaBrowser.php
Is a requirement to test com_users with different profiles
=> Allow to log in as different user

src/JoomlaBrowser.php
When English is already selected, sometimes the installation page text still appears in the browser's language instead of the one selected. The installation will fail because the "Next" selector will not be found.
This PR fixes it by first selecting a random language to force refreshing of the lang strings when English is selected
=> Force language change during installation

src/JoomlaBrowser.php
Creates a Joomla menu item, for example:
$I->createMenuItem('My title', 'Weblinks', 'List All Web Link Categories', 'Main Menu');
=> [add] createMenuItem

src/JoomlaBrowser.php
I recently encountered an issue with the waitFor time while installing one of the extensions. I think 30 sec is not enough time. Hence I have increased the time limit to 60 sec.
I have also tried to add check for Notices and Warnings, and removed the complex Xpaths for New and Save buttons on Menu Item Creation.
=> Fixing Issue and Improving the Code Readability on Joomla! Browser

src/JoomlaBrowser.php
Also adds support for multilingual
cc: @yvesh
=> Avoid false positives creating a menu

src/JoomlaBrowser.php
This should fix 
https://github.com/joomla-projects/joomla-browser/issues/45
https://github.com/joomla-projects/joomla-browser/pull/51
I couldn't make it work with waitForElementChange, but this solution is basically the same with JS. The js is executed until the condition is met(the field becomes disabled). If this happens within 60s, then we go further...
=> wait for the folder to be deleted and then go further!

src/JoomlaBrowser.php
=> Removed the adding of ending slash

src/JoomlaBrowser.php
This pull adds a hotfix solution for when selecting by label fails like in https://github.com/joomla-projects/joomla-browser/issues/85
=> Add selectOptionInChosenByID

src/JoomlaBrowser.php
It performs better locating the Log out button
=> Improved locator for Front End Login function

src/JoomlaBrowser.php
This commit adds more time before timeout while locating the elements. Also makes the xpath more specific to increase performance
=> Avoid False positives on Admin logout

src/JoomlaBrowser.php
There was a missing `wait` that causes sometime false positives.
=> Avoid false positives in Administrator Login

src/JoomlaBrowser.php
We need to add some wait times after the choosen, because else the tests
will fail on wamp.
=> Add wait time, to support tests on windows with wamp.

src/JoomlaBrowser.php
Temporal Reverts joomla-projects/joomla-browser#82
due to:
=> Revert "Adding a tool bar logic for smaller screen resolutions "

src/JoomlaBrowser.php
Uninstall method in Joomla 3.5.x has a popup when uninstalling any extension. This popup was not in 3.4.x series:
After this get merged we should release Joomla-browser 3.5.1.0
=> Add compatibility with Joomla 3.5.1 changed uninstalling method
